services:
  db:
    image: mysql:8.3.0
    restart: always
    volumes:
      - samsung:/var/lib/mysql
      - ${HOST_DATA_DIR}:/samsung_ecom
      - ./${SQL_FILE}:/docker-entrypoint-initdb.d/database-init.sql:ro
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_DATABASE: samsung_ecom
      MYSQL_USER: slave
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_user_password
    secrets:
      - mysql_root_password
      - mysql_user_password
    ports:
      - 3306:3306
    command: >
      --innodb_directories="/samsung_ecom"
      --default-authentication-plugin=caching_sha2_password

secrets:
  mysql_root_password:
    file: mysql_root_password_secret.txt
  mysql_user_password:
    file: mysql_user_password_secret.txt

volumes:
  samsung:
